steps:

    # build
    - name: 'docker'
      args: ['build','-t','app','.']

    # migrate
    - name: 'docker'
      args: ['run','app','python3','manage.py','migrate']

    - name: 'docker'
      args: ['run','app','python3','manage.py','test']